### ISSUE TITLE
Create Signup View

### ISSUE THREAD

**Issue by ZeroCoolHacker** [ZeroCoolHacker/easy-school#17]
Create Signup View using django class based views

**Comment by adamzavacky** [comment]
Hello , i would like to work on this issue.

**Comment by ZeroCoolHacker** [comment]
That would be appreciated.

**Comment by ZeroCoolHacker** [comment]
> Hello , i would like to work on this issue. I am mid skilled developer in python
Sure!
Waiting for the pull request

**Comment by ZeroCoolHacker** [comment]
closed in #20
