### ISSUE TITLE
Create Login View

### ISSUE THREAD

**Issue by ZeroCoolHacker** [ZeroCoolHacker/easy-school#18]
Create Login View using Django Class Based Views

**Comment by adamzavacky** [comment]
Hello , i would also like to do on this issue :)

**Comment by ZeroCoolHacker** [comment]
Submit a pull request when you are done.

**Comment by MohanChhabaria** [comment]
#31 Solves this issue. You can review it.

**Comment by ZeroCoolHacker** [comment]
Thank you @MohanChhabaria
