### ISSUE TITLE
Display Fee Deposit Slip After Submission

### ISSUE THREAD

**Issue by ZeroCoolHacker** [ZeroCoolHacker/easy-school#19]
A Fee Deposit Slip or Reciept Should be Created After the Fee is deposited.

**Comment by marosmola** [comment]
Hi @ZeroCoolHacker can i work on this!

**Comment by ZeroCoolHacker** [comment]
@marosmola Submit a PR when you are done

**Comment by MohanChhabaria** [comment]
@ZeroCoolHacker  How fee submission procedure is handled ? I there any view ready for it .

**Comment by ZeroCoolHacker** [comment]
@MohanChhabaria @marosmola  I appreciate your interest in the project. 
I have updated the project to use the latest Django 3 with modern python features such as formatted strings.
I am going to release the first final version on Sunday. 
Changes expected
- Student Fee reduced to just 1 model for simplicity
- Teacher Salary model created
- Export data as csv

So it will be usable by any school then. I am planning on version 2 of this app after that, which will include extra features which we can discuss if you wish so.
I am closing this issue as of now.

**Comment by marosmola** [comment]
@ZeroCoolHacker do you have plans about future features? I am interested in contributing. Please let me know if i can help?

**Comment by ZeroCoolHacker** [comment]
@marosmola The idea was to have a simple system that can be used by small schools for management.
I am doing a release on next saturday.
I am open to new ideas. You can open an issue suggesting new features. I also have some in mind i will post in that issue and we can discuss

**Comment by marosmola** [comment]
@ZeroCoolHacker i saw there is one pending issue in READMEs todo:

> Add graph comparing teacher salaries given vs student's fee collected

Is this some difference based on months?

**Comment by ZeroCoolHacker** [comment]
@marosmola Basically there should be some way of seeing the profit the school owner has made. 
Tota* salary given this month - Total fee collected

**Comment by marosmola** [comment]
> @marosmola Basically there should be some way of seeing the profit the school owner has made.
> Profit = Total salary given this month - Total fee collected

Can you create feature issue for me? I will work on this this week :)

**Comment by ZeroCoolHacker** [comment]
> > @marosmola Basically there should be some way of seeing the profit the school owner has made.
> > Profit = Total salary given this month - Total fee collected
> 
> @ZeroCoolHacker Can you create feature issue for me? I will work on this this week :)

https://github.com/ZeroCoolHacker/easy-school/issues/48
