### ISSUE TITLE
Can not calculate percentage

### ISSUE THREAD

**Issue by ZeroCoolHacker** [ZeroCoolHacker/easy-school#3]
in students/admin.py i need to calculate the percentage value for each bar in bar graph. I can't figure out the formula.

**Comment by Argetan** [comment]
What exactly are you trying to calculate? I assume you are talking about your code starting at line [179](https://github.com/ZeroCoolHacker/easy-school/blob/master/easyschool/students/admin.py#L179).

**Comment by Argetan** [comment]
Alright, I assume that `x['total']` is what you collected in a single month (in your example January) and `high` is what you collected in 6 months?

**Comment by ZeroCoolHacker** [comment]
no high is the highest among them.
You have to calculate the sum of all x['total']  and divide it by the current x['total']*100.
thats what i understand right now. 
my classmate gave me this weird formula that doesnt work.

**Comment by Argetan** [comment]
Alright, I'm not sure what your goal is here but I'll give a few examples:

Let's say we have a value `current` which is the sum of the fees in a specific month and `total` which is the sum of the fees over multiple months.

If you do `(current/total) * 100` it will give you a value between `0` and `100`, this value indicates how much you made that month relatively seen to all the other months combined.

In another scenario where we still have `current` which is still the sum of fees in a specific month and `high` which is the highest fee, you have ever gotten in a month.

If you do `(current/high) * 100` it will give you a value between `0` and `100` again, this value indicates how much you made relative to the month in which you made the most money.

**Comment by Argetan** [comment]
On a side note, your current `high` is not giving the highest fee paid in a single month, but the total of fees in the period they were added to the system.

Par example I created a few fees to test things today for the months January, February and March, and the high is `80` but that is the sum of those 3 months combined. So there already is a possible error there.

**Comment by ZeroCoolHacker** [comment]
> On a side note, your current `high` is not giving the highest fee paid in a single month, but the total of fees in the period they were added to the system.
> 
> Par example I created a few fees to test things today for the months January, February and March, and the high is `80` but that is the sum of those 3 months combined. So there already is a possible error there.

Thanks man!
Yeah i just realized that the whole calculation is buggy.
It would be helpful of you to correct that.
