### ISSUE TITLE
Export Data from django admin in CSV Format

### ISSUE THREAD

**Issue by ZeroCoolHacker** [ZeroCoolHacker/easy-school#33]
All admin views should export data in csv format.

**Comment by mrunderline** [comment]
seems good, can I work on it?

**Comment by ZeroCoolHacker** [comment]
@mrunderline Sure
Submit a PR when you are done.

**Comment by ZeroCoolHacker** [comment]
@all-contributors please add @mrunderline  for csv_export

**Comment by ZeroCoolHacker** [comment]
@all-contributors please add @mrunderline for code
