### ISSUE TITLE
Display profit per month

### ISSUE THREAD

**Issue by ZeroCoolHacker** [ZeroCoolHacker/easy-school#48]
We need a way to display profit per month. 
It can be as simple as total_profit_in_x_month = total_fee_collected_in_x_month - total_salary_given_in_x_month.
We can use graph or just a comparison table. anything. We need this feature in the first release.

**Comment by marosmola** [comment]
@ZeroCoolHacker i'm on it!

**Comment by ZeroCoolHacker** [comment]
@marosmola Submit a PR when you are done

**Comment by marosmola** [comment]
@ZeroCoolHacker i created graph today. Looks pretty nice and does not have external dependencies except `<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>` in the html template. 

What do you think? What could be the possible improvements in the design? I also have a question regarding teacher salary. It has two attributes `valid_until` and `paid_on` which should i use when displaying the graph? The same question for student fee model. 

For now i have used `paid_on` and `date_submitted` attributes to match payments to actual month.

![Screenshot from 2020-10-28 22-08-30](https://user-images.githubusercontent.com/19537488/97497068-39b01180-196a-11eb-9644-c45198a2257b.png)

**Comment by ZeroCoolHacker** [comment]
@marosmola Overall this looks good. 
Can we try some lighter colors for the graph though?

**Comment by marosmola** [comment]
@ZeroCoolHacker i added profit column and also change colors to match theme. What do you think?
![Screenshot from 2020-10-31 16-00-35](https://user-images.githubusercontent.com/19537488/97782535-5038b180-1b92-11eb-91b3-bbd837e6eaac.png)
