### ISSUE TITLE
Create Guardian Model

### ISSUE THREAD

**Issue by ZeroCoolHacker** [ZeroCoolHacker/easy-school#7]
Currently we are using custom fields in the student model itself. which has father_name, father_cnic etc fields.
There should be a guardian model having following fields
- Name
- Gender
- Relation to student
- Social Security Number
- Phone Number
- Profession

**Comment by davidkarabas** [comment]
@ZeroCoolHacker I want to work on this issue. Can I take this? Is it still actuall?

**Comment by davidkarabas** [comment]
On it
